quarkus.application.name=car-rental-api

# Configuracion de MongoDB

# Nombre de la base de datos de MongoDB
quarkus.mongodb.database=car-rental
# Dirección del servidor de MongoDB
#Conectarse con mongo atlas
quarkus.mongodb.connection-string=mongodb://localhost:27017

# Configuracion de Logging (por defecto)

# Nivel de log global para todos los perfiles, a menos que se sobreescriba.
quarkus.log.level=INFO
# Configuración del formato de la consola
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n