#Sobrescribe la configuración de Logging para desarrollo
# Aumentamos el nivel de log para depuración
quarkus.log.level=DEBUG

# Habilitamos el logging para categorías específicas en modo debug
quarkus.log.category."org.jegdev.car_rental".level=DEBUG

# Mostramos el color para una mejor legibilidad en la consola
quarkus.log.console.color=true