#Sobrescribe la configuración de Logging para desarrollo
# Aumentamos el nivel de log para depuración
quarkus.log.level=INFO

# Habilitamos el logging para categorías específicas en modo debug
quarkus.log.category."org.jegdev.car_rental".level=DEBUG

# Mostramos el color para una mejor legibilidad en la consola
quarkus.log.console.color=true

# Deshabilitar testcontainer para MongoDB en modo de desarrollo
quarkus.mongodb.devservices.enabled=false

# Deshabilitar el uso de imagenes de contenedor para pruebas
quarkus.container-image.disable-for-tests=true