quarkus.application.name=car-rental-api

# Configuracion de MongoDB
# Usa una variable de entorno para la cadena de conexión de MongoDB Atlas
quarkus.mongodb.connection-string=${MONGO_CONNECTION_STRING}
# Nombre de la base de datos de MongoDB
quarkus.mongodb.database=${MONGO_DATABASE_NAME}

# Configuracion de Logging (por defecto)
quarkus.log.level=INFO
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n

# Configuracion de la API de Rick and Morty
org.jegdev.car_rental.api.rickAdnMorty.client.RickAndMortyApi/mp-rest/url=https://rickandmortyapi.com/api

# URL base (WeatherAPI v1)
weatherapi/mp-rest/url=https://api.weatherapi.com

# Tu API key
weatherapi.key=${WEATHERAPI_KEY}